{% set name = "des-montara" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/des-science/montara/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c106f0494c38aef3bc39c6d1f357e903e23c6f4ac7f4f95b72d0ee7e0c24e8d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - galsim
    - fitsio
    - numpy
    - astropy
    - des-eastlake
    - galsim_extra
    - importlib_metadata
    - cfitsio

test:
  imports:
    - montara

about:
  home: https://github.com/des-science/montara
  summary: package for simulating DES Y6 data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
