{% set name = "des-montara" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/des-science/montara/archive/refs/tags/{{ version }}.tar.gz
  sha256: 02d1a24311367781c1c81b67d9f8e8a271b0429795f58b9110ea33b33932f3ac

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - galsim
    - fitsio
    - numpy
    - astropy
    - des-eastlake
    - galsim_extra
    - importlib_metadata
    - cfitsio

test:
  imports:
    - montara

about:
  home: https://github.com/des-science/montara
  summary: package for simulating DES Y6 data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
